import type { Listing } from "./types";

const DAY = 24 * 60 * 60 * 1000;
const now = Date.UTC(2026, 7, 21);

export const CATALOG: Listing[] = [
  {
    id: "cvt-belt",
    source: "catalog",
    title: "Used ATV drive belts — pair, ready to install",
    description:
      "Pair of used ATV drive belts pulled from a working Sportsman. No glazed spots, no chunks missing. Stored dry. Good spare or daily belt if you measure your clutch width first.",
    category: "atv",
    raceSurface: null,
    partType: "Drive belt",
    fitment: "Polaris Sportsman 450 / 570, 2016–2023",
    condition: "used",
    price: 89,
    location: "Clay, NY",
    photo: "/parts/cvt-belt.jpg",
    tags: ["belt", "cvt", "clutch", "sportsman", "polaris"],
    highlights: ["Pair included", "No cracks through the carcass", "Garage kept"],
    createdAt: now - 1 * DAY,
  },
  {
    id: "a-arm",
    source: "catalog",
    title: "Front A-arm — Honda FourTrax Rancher",
    description:
      "Passenger-side front A-arm off a Rancher. Bushings are tired, ball joint still tight. Straight tubes, no bends from rocks. Paint is original and faded. Good core or trail spare.",
    category: "atv",
    raceSurface: null,
    partType: "A-arm",
    fitment: "Honda FourTrax Rancher 420, 2007–2014",
    condition: "used",
    price: 140,
    location: "Watertown, NY",
    photo: "/parts/a-arm.jpg",
    tags: ["a-arm", "suspension", "rancher", "honda", "front"],
    highlights: ["Straight tubes", "Ball joint tight", "Needs bushings"],
    createdAt: now - 2 * DAY,
  },
  {
    id: "winch",
    source: "catalog",
    title: "2,500 lb ATV winch with synthetic rope",
    description:
      "Compact winch, synthetic line, hawse fairlead. Used two seasons on a Can-Am Outlander. Motor pulls strong, remote still clicks. Mount plate not included — measure your bumper.",
    category: "atv",
    raceSurface: null,
    partType: "Winch",
    fitment: "Universal ATV / UTV bumper mount",
    condition: "like-new",
    price: 165,
    location: "Syracuse, NY",
    photo: "/parts/winch.jpg",
    tags: ["winch", "recovery", "synthetic", "can-am", "outlander"],
    highlights: ["Synthetic rope", "Remote included", "Strong pull"],
    createdAt: now - 3 * DAY,
  },
  {
    id: "shock",
    source: "catalog",
    title: "Rear gas shock with piggyback reservoir",
    description:
      "Rear shock off a Grizzly 700. Reservoir holds pressure, shaft is straight, no pitting. Spring still has life. Valving is stock. Ready to bolt on after a wipe-down.",
    category: "atv",
    raceSurface: null,
    partType: "Shock",
    fitment: "Yamaha Grizzly 700, 2007–2015",
    condition: "used",
    price: 210,
    location: "Utica, NY",
    photo: "/parts/shock.jpg",
    tags: ["shock", "suspension", "grizzly", "yamaha", "piggyback"],
    highlights: ["Holds nitrogen", "Straight shaft", "Stock valving"],
    createdAt: now - 4 * DAY,
  },
  {
    id: "piston",
    source: "catalog",
    title: "450cc piston and rings — top-end refresh",
    description:
      "Forged piston and ring set from a CRF450R top-end. Crown is carboned but not holed. Ring lands are sharp. Measure skirt and decide if you reuse or keep as a pattern. Wrist pin not included.",
    category: "dirtbike",
    raceSurface: null,
    partType: "Piston",
    fitment: "Honda CRF450R, 2017–2020",
    condition: "for-parts",
    price: 95,
    location: "Rochester, NY",
    photo: "/parts/piston.jpg",
    tags: ["piston", "top-end", "crf450", "honda", "rings"],
    highlights: ["Rings included", "No hole in the crown", "Pattern or rebuild"],
    createdAt: now - 5 * DAY,
  },
  {
    id: "swingarm",
    source: "catalog",
    title: "Aluminum swingarm — KX250F",
    description:
      "Used swingarm with honest roost rash. Pivot is true, no cracks at the chain slider bosses. Bearings not included. Chain slider is chewed — budget a new one. Straight and race-usable.",
    category: "dirtbike",
    raceSurface: null,
    partType: "Swingarm",
    fitment: "Kawasaki KX250F, 2017–2020",
    condition: "used",
    price: 380,
    location: "Buffalo, NY",
    photo: "/parts/swingarm.jpg",
    tags: ["swingarm", "chassis", "kx250f", "kawasaki", "aluminum"],
    highlights: ["No cracks", "True pivot", "Needs chain slider"],
    createdAt: now - 6 * DAY,
  },
  {
    id: "forks",
    source: "catalog",
    title: "Inverted front forks — gold stanchions",
    description:
      "USD fork set off a YZ450F. Stanchions are clean, no deep chips. Seals were changed last season. Inners unknown — treat as a refresh candidate. Axle and pinch bolts included.",
    category: "dirtbike",
    raceSurface: null,
    partType: "Front forks",
    fitment: "Yamaha YZ450F, 2018–2022",
    condition: "used",
    price: 520,
    location: "Albany, NY",
    photo: "/parts/forks.jpg",
    tags: ["forks", "usd", "yz450f", "yamaha", "suspension"],
    highlights: ["Seals recently done", "Clean tubes", "Axle included"],
    createdAt: now - 7 * DAY,
  },
  {
    id: "exhaust",
    source: "catalog",
    title: "Full exhaust — 250F four-stroke",
    description:
      "Header, mid, and muffler. Carbon-look end cap still intact. Dents are cosmetic. Packing is original and tired — plan a repack. Mounts line up on a generic 250F. No spark arrestor.",
    category: "dirtbike",
    raceSurface: null,
    partType: "Exhaust",
    fitment: "250F four-stroke (verify header flange)",
    condition: "used",
    price: 310,
    location: "Binghamton, NY",
    photo: "/parts/exhaust.jpg",
    tags: ["exhaust", "muffler", "header", "250f", "pipe"],
    highlights: ["Full system", "End cap intact", "Needs packing"],
    createdAt: now - 8 * DAY,
  },
  {
    id: "sprocket",
    source: "catalog",
    title: "50-tooth rear sprocket",
    description:
      "Steel rear sprocket, 50T. Teeth still have a square profile — not hooked. Bolt holes are round. Good for a 125/250 conversion or a spare in the truck. Clean it and it looks new.",
    category: "dirtbike",
    raceSurface: null,
    partType: "Sprocket",
    fitment: "125 / 250, 50T, standard bolt pattern",
    condition: "new",
    price: 42,
    location: "Ithaca, NY",
    photo: "/parts/sprocket.jpg",
    tags: ["sprocket", "50t", "drivetrain", "rear", "steel"],
    highlights: ["Square teeth", "Never mounted", "50 tooth"],
    createdAt: now - 9 * DAY,
  },
  {
    id: "skid-plate",
    source: "catalog",
    title: "Diamond-plate aluminum skid plate",
    description:
      "Underbody armor, aluminum diamond plate. Scratches from rocks, no tears. Mount tabs are straight. Fits a Tacoma / 4Runner style mid-size with minor drilling. Hardware not included.",
    category: "truck",
    raceSurface: null,
    partType: "Skid plate",
    fitment: "Mid-size truck (Tacoma / 4Runner style)",
    condition: "like-new",
    price: 245,
    location: "Denver, CO",
    photo: "/parts/skid-plate.jpg",
    tags: ["skid", "armor", "aluminum", "tacoma", "4runner"],
    highlights: ["No tears", "Straight tabs", "Diamond plate"],
    createdAt: now - 2 * DAY,
  },
  {
    id: "mud-tire",
    source: "catalog",
    title: '35" mud-terrain tire — 35x12.50R17',
    description:
      "One 35-inch mud tire with plenty of lug left. Dried mud in the voids. No cords showing, no sidewall cuts. Sold as a single — match the DOT if you need a pair. Great spare or staggered setup.",
    category: "truck",
    raceSurface: null,
    partType: "Tire",
    fitment: "35x12.50R17, 8-ply",
    condition: "used",
    price: 180,
    location: "Moab, UT",
    photo: "/parts/mud-tire.jpg",
    tags: ["tire", "35", "mud", "mt", "17-inch"],
    highlights: ["No cords", "Deep lugs", "Sold as a single"],
    createdAt: now - 1 * DAY,
  },
  {
    id: "light-bar",
    source: "catalog",
    title: "50-inch LED light bar, straight",
    description:
      "Slim combo-beam LED bar. Housing is clean, all diodes light. Comes with bottom mounts. Wiring pigtail included, no switch. Universal — drill your bumper or use a roof basket.",
    category: "truck",
    raceSurface: null,
    partType: "Light bar",
    fitment: "Universal 50-inch, 12V",
    condition: "new",
    price: 95,
    location: "Austin, TX",
    photo: "/parts/light-bar.jpg",
    tags: ["led", "light bar", "50-inch", "lighting", "12v"],
    highlights: ["All diodes work", "Mounts included", "Combo beam"],
    createdAt: now - 3 * DAY,
  },
  {
    id: "ski",
    source: "catalog",
    title: "Snowmobile front ski with runner",
    description:
      "Left-side ski, plastic body, carbide runner is worn but not through. Spindle mount is true. Good spare for a trail sled or a core if you recarbide. No shocks included.",
    category: "snowmobile",
    raceSurface: null,
    partType: "Ski",
    fitment: "Trail sled, verify spindle bolt pattern",
    condition: "used",
    price: 120,
    location: "Watertown, NY",
    photo: "/parts/ski.jpg",
    tags: ["ski", "snowmobile", "carbide", "sled", "front"],
    highlights: ["Mount is true", "Runner still there", "No spindle"],
    createdAt: now - 4 * DAY,
  },
  {
    id: "beadlock",
    source: "catalog",
    title: '15" beadlock wheel — dirt late model',
    description:
      "Steel beadlock pulled off a dirt late model. Clay packed in the wells, hardware is complete. Ring is true, no cracked windows. Sold as a single — match offset before you pair it. Good spare or a core if you powder coat.",
    category: "racecar",
    raceSurface: "dirt",
    partType: "Beadlock wheel",
    fitment: "15-inch dirt late model / modified, verify bolt pattern",
    condition: "used",
    price: 275,
    location: "Oswego, NY",
    photo: "/parts/beadlock.jpg",
    tags: ["beadlock", "wheel", "dirt", "late model", "15-inch"],
    highlights: ["Hardware included", "No cracked windows", "Sold as a single"],
    createdAt: now - 1 * DAY,
  },
  {
    id: "race-caliper",
    source: "catalog",
    title: "Racing brake caliper — asphalt late model",
    description:
      "Used red racing caliper off an asphalt late model. Pistons move, no seized corners. Banjo bolt included, pads not included. Housing is clean besides honest heat tint. Measure piston size before you bolt it on.",
    category: "racecar",
    raceSurface: "asphalt",
    partType: "Brake caliper",
    fitment: "Asphalt late model, verify piston count and mount",
    condition: "used",
    price: 190,
    location: "Watkins Glen, NY",
    photo: "/parts/race-caliper.jpg",
    tags: ["caliper", "brake", "asphalt", "late model", "racing"],
    highlights: ["Pistons move", "Banjo included", "Pads not included"],
    createdAt: now - 2 * DAY,
  },
  {
    id: "sprint-wing",
    source: "catalog",
    title: "Aluminum nose wing — dirt sprint",
    description:
      "Used aluminum nose wing with honest roost rash. Rivets are tight, no folded leading edge. Sideboard is straight. Good spare for a 360/410 sprint or a core if you reskin. Mounting tabs included.",
    category: "racecar",
    raceSurface: "dirt",
    partType: "Nose wing",
    fitment: "Dirt sprint car, verify tab pattern",
    condition: "used",
    price: 340,
    location: "Weedsport, NY",
    photo: "/parts/sprint-wing.jpg",
    tags: ["wing", "sprint", "dirt", "aluminum", "nose"],
    highlights: ["Rivets tight", "Straight sideboard", "Tabs included"],
    createdAt: now - 3 * DAY,
  },
  {
    id: "bypass-shock",
    source: "catalog",
    title: "Long-travel bypass shock — offroad race truck",
    description:
      "Used 3.0 bypass pulled off a desert race truck. Reservoir is tight, shaft is straight, no blown seal spray. Valving is race-stiff — not a grocery-getter shock. Mounting eyes included, no reservoir hose. Measure compressed and extended length before you bolt it on.",
    category: "racecar",
    raceSurface: "offroad",
    partType: "Bypass shock",
    fitment: "Trophy truck / Ultra4 / desert race truck, verify eye-to-eye",
    condition: "used",
    price: 420,
    location: "Clay, NY",
    photo: "/parts/shock.jpg",
    tags: ["shock", "bypass", "offroad", "trophy truck", "long travel"],
    highlights: ["Shaft straight", "No blown seal", "Eyes included"],
    createdAt: now - 4 * DAY,
  },
];


export const SAMPLES = [
  {
    id: "cvt-belt",
    label: "Drive belt",
    photo: "/parts/cvt-belt.jpg",
    category: "atv" as const,
  },
  {
    id: "piston",
    label: "Piston",
    photo: "/parts/piston.jpg",
    category: "dirtbike" as const,
  },
  {
    id: "mud-tire",
    label: "Mud tire",
    photo: "/parts/mud-tire.jpg",
    category: "truck" as const,
  },
  {
    id: "ski",
    label: "Ski",
    photo: "/parts/ski.jpg",
    category: "snowmobile" as const,
  },
  {
    id: "beadlock",
    label: "Beadlock",
    photo: "/parts/beadlock.jpg",
    category: "racecar" as const,
  },
];

export function getCatalogById(id: string) {
  return CATALOG.find((item) => item.id === id);
}
